/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Trung Le (https://sketchfab.com/trungtuanle)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/d20-black-9537df0bf5834082918d582461571b40
Title: D20 Black
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    D20_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function DiceModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/d20_black/scene.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
       
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.D20_Material002_0.geometry}
        material={materials['Material.002']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1}
      />
    </group>
  )
}

useGLTF.preload('/public/d20_black/scene.gltf')