/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGLTF, PerspectiveCamera, useHelper } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
  }
  materials: {}
}

export function TvModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/prototype1.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.895}
        position={[7.359, 4.958, 6.926]}
        rotation={[-0.627, 0.71, 0.441]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 2.551, 0.042]}
        scale={1.577}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0.887, 1.328, -0.526]}
        rotation={[0, 0, 1.571]}
        scale={0.054}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.887, 1.328, -0.165]}
        rotation={[0, 0, 1.571]}
        scale={0.054}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.887, 1.328, -0.165]}
        rotation={[0, 0, 1.571]}
        scale={0.054}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0.887, 1.328, 0.533]}
        rotation={[0, 0, 1.571]}
        scale={0.054}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.887, 1.328, 0.172]}
        rotation={[0, 0, 1.571]}
        scale={0.054}
      />
    </group>
  )
}

useGLTF.preload('/public/prototype1.gltf')

